version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - chess-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge
